#!/bin/bash
# http://www.chessarch.com/library/0000_eco/index.shtml
# cat a00_a99.shtml b00_b99.shtml c00_c99.shtml d00_d99.shtml e00_e99.shtml | grep shtml | sed -e 's/\(.*\)\(".*"\)\(.*\)/\2/g' | sed -e 's/"//g' >all.txt
# for i in `cat location/all.txt`; do wget http://www.chessarch.com/library/0000_eco/$i; done
# for i in source/*.shtml; do ./conv $i `echo $i | sed s/shtml/txt/g | sed s/source/txt/g` ; done

fn_in=$1
fn_out=$2

#fn="d00_d05.shtml"

cat $fn_in | perl -p -e "s/\r//g"            \
           | perl -p -e "s/\205/. ... /g"    \
           | sed ':r;$!{N;br};s/\n(/(/g'     \
           | sed ':r;$!{N;br};s/\n\([A-Z0-9]\)/ \1/g'     \
           | grep "font color"               \
           | sed -e 's/<b>/E /g'           \
           | sed -e 's/<[^>]*>//g'           \
           | sed -e 's/E 1/C 1/g'           \
      >$fn_out


#        | sed ':r;$!{N;br};s/\n[A-Z0-9]/MMM/g'     \
